### ISSUE TITLE
Custom-database CLI

### ISSUE THREAD

**Issue by zmahnoor14** [sirius-ms/sirius#106]
Hello SIRIUS developers,

I am currently using SIRIUS 5.6.3 CLI version and following the documentation: [SIRIUS Documentation - Custom Database](https://boecker-lab.github.io/docs.sirius.github.io/cli-standalone/#custom-database-tool)

so according to current documentation:  

`sirius --input /Users/mahnoor/SL_Sirius.tsv --name SL_Sirius custom-db --output /Users/mahnoor/SIRIUS`

However, SIRIUS returns errors like: unknown options: "--input" or "output".

I think this needs an update as this command was working on SIRIUS4. Could you take a look into this issue?

Thanks,
Mahnoor

**Comment by simcoxkm** [comment]
The custom database feature is also not working in the GUI. When I try to create a database by either typing in the SMILES code and hitting "open/create database" or by directly uploading a csv, I receive this error: 

java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at de.unijena.bioinf.storage.blob.Compressible$Compression.valueOf(Compressible.java:44)
	at de.unijena.bioinf.storage.blob.CompressibleBlobStorage.of(CompressibleBlobStorage.java:40)
	at de.unijena.bioinf.chemdb.custom.CustomDatabase.open(CustomDatabase.java:99)
	at de.unijena.bioinf.chemdb.SearchableDatabases.loadCustomDatabaseFromLocation(SearchableDatabases.java:195)
	at de.unijena.bioinf.ms.gui.fingerid.custom_db.DatabaseDialog$ImportDatabaseDialog.lambda$runImportJob$2(DatabaseDialog.java:344)
	at de.unijena.bioinf.jjobs.LoadingBackroundTask$1.compute(LoadingBackroundTask.java:35)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Hope this helps!

**Comment by my3sonsMN** [comment]
Wondering if there has been a solution to the create custom database feature in the software.  As others have commented the addition of smiles strings still doesn't seem to be working.  would love to have a way to bring in exports from other databases to help build up the compounds thank you  David Weil

**Comment by gdiazcruz** [comment]
Hello!
I am having the same (or similar) issue with the 5.8.3 version:

java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at de.unijena.bioinf.storage.blob.Compressible$Compression.valueOf(Compressible.java:44)
	at de.unijena.bioinf.storage.blob.CompressibleBlobStorage.of(CompressibleBlobStorage.java:40)
	at de.unijena.bioinf.chemdb.custom.CustomDatabase.open(CustomDatabase.java:99)
	at de.unijena.bioinf.chemdb.SearchableDatabases.loadCustomDatabaseFromLocation(SearchableDatabases.java:195)
	at de.unijena.bioinf.ms.gui.fingerid.custom_db.DatabaseDialog$ImportDatabaseDialog.lambda$runImportJob$2(DatabaseDialog.java:349)
	at de.unijena.bioinf.jjobs.LoadingBackroundTask$1.compute(LoadingBackroundTask.java:35)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by my3sonsMN** [comment]
Do you think you can let me know when you have a solution.

Thank you

David weil

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YasinEl** [comment]
Hello SIRIUS scientists :)

in SIRIUS 6.0.0 under Windows 11 I am still running into the same problem (see below). Also I think the documentation should be updated regarding arguments (--location instead of --output).

Thanks!

```
sirius custom-db -i structures.tsv --name tmp_sirius_db --location output\

java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at de.unijena.bioinf.storage.blob.Compressible$Compression.valueOf(Compressible.java:44)
	at de.unijena.bioinf.storage.blob.CompressibleBlobStorage.of(CompressibleBlobStorage.java:40)
	at de.unijena.bioinf.chemdb.custom.CustomDatabases.open(CustomDatabases.java:191)
	at de.unijena.bioinf.chemdb.custom.CustomDatabases.createOrOpen(CustomDatabases.java:207)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.compute(CustomDBOptions.java:188)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.compute(CustomDBOptions.java:144)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:124)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
