### ISSUE TITLE
SIRIUS 6: no LC-MS chromatograms

### ISSUE THREAD

**Issue by JethroHemmann** [sirius-ms/sirius#157]
Thanks for adding exciting new features to SIRIUS 6! :-)

When testing the new version with mzML files, I noticed that the LC-MS chromatogram is not working anymore and I just get empty plots. 
Is this a bug?

![grafik](https://github.com/sirius-ms/sirius/assets/6010271/35001d70-4931-4a51-993a-d2c28982cc44)

**Comment by JethroHemmann** [comment]
Ah, it works though when importing and aligning multiple files. But it used toi work with a single file as well.

**Comment by kaibioinfo** [comment]
Hi,
when importing single files there is no "preprocessing" going on. Instead, it just extracts all MS/MS from the file. It's quite important to import all the LCMS files at once to get a proper feature detection and isotope pattern extraction.

I have to think about if it makes sense to have a proper reworked "single file import".

**Comment by JethroHemmann** [comment]
Thanks for your response! 

I often just load a single representative file to save some time, if I am just interested in a few specific metabolites. And in SIRIUS 5, the LC-MS tab also showed the peak in that case. So would be nice if that worked again in SIRIUS 6 :-)

**Comment by typewritermonkey** [comment]
Thanks for developing Sirius 6! 

I also tried to do a test run with a single mzml file and had problems. Like not showing the chromatograms and not being able to filter out the bad ones before computing all lol. I just tried to import 3 mzmls at once and got this error message:

Error when importing data! Cause: java.lang.Exception: java.lang.IllegalArgumentException: Given retention time middle is not in range: 99.03114129675636 is not in [99.03114129675637, 103.02829512486207]
java.lang.Exception: java.lang.IllegalArgumentException: Given retention time middle is not in range: 99.03114129675636 is not in [99.03114129675637, 103.02829512486207]
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob.updateAndCheckIfDone(SseProgressJJob.java:129)
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:76)
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:65)
	at de.unijena.bioinf.sse.FluxToFlowBroadcast.lambda$onNext$7(FluxToFlowBroadcast.java:103)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at de.unijena.bioinf.sse.FluxToFlowBroadcast.onNext(FluxToFlowBroadcast.java:99)
	at de.unijena.bioinf.ms.nightsky.sdk.NightSkyClient.lambda$enableEventListening$3(NightSkyClient.java:198)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:446)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:533)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by kaibioinfo** [comment]
Okay, that's definitely a bug. We will fix that with the next patch.

**Comment by mfleisch** [comment]
Hey,
the strange behaviour for 1 or 2 mzml files should be fixed in 6.0.4.

I close the issue, please reopen if the problem still persists.
