### ISSUE TITLE
custom database creation from CLI does not work

### ISSUE THREAD

**Issue by YasinEl** [sirius-ms/sirius#174]
Hello SIRIUS scientists :)

in SIRIUS 6.0.0 under Windows 11 I am still running into the same problem as described in https://github.com/sirius-ms/sirius/issues/106 which has been marked as completed. Specifically, creating Custom databases does not seem to work from the CLI as shown below. Notably using the very same file `structures.tsv` in the GUI is successful. Would be great to get help or a fix for this. 

Also as a side note, I think the documentation should be updated regarding arguments (--location instead of --output).

Thanks!

```
sirius custom-db -i structures.tsv --name tmp_sirius_db --location output\

java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at de.unijena.bioinf.storage.blob.Compressible$Compression.valueOf(Compressible.java:44)
	at de.unijena.bioinf.storage.blob.CompressibleBlobStorage.of(CompressibleBlobStorage.java:40)
	at de.unijena.bioinf.chemdb.custom.CustomDatabases.open(CustomDatabases.java:191)
	at de.unijena.bioinf.chemdb.custom.CustomDatabases.createOrOpen(CustomDatabases.java:207)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.compute(CustomDBOptions.java:188)
	at de.unijena.bioinf.ms.frontend.subtools.custom_db.CustomDBOptions$CustomDBWorkflow.compute(CustomDBOptions.java:144)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:124)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by mfleisch** [comment]
Hey Yasin,
just tested it myself with SIRIUS 6.0.4 and the import seems to work fine. The command is just slightly different in SIRIUS 6. The `--location` needs to point to the **file** where the db shall be stored.  

`sirius custom-db -i structures.tsv --name tmp_sirius_db --location output\myDB.siriusdb`

The command was wrong in the docu example (fixed) but correct in the cli help.
