### ISSUE TITLE
Jobs failed in Summaries Output

### ISSUE THREAD

**Issue by Andrea20230927** [sirius-ms/sirius#189]
When "Write Summaries for whole project",
only partial structure appears in output folder (113/2324),
and the "jobs" appear FAILED 

嚴重: <217>[BackgroundRunJob-217] Failed!
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null
        at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlStructureSummaryWriter.writeStructureCandidate(NoSqlStructureSummaryWriter.java:110)
        at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:221)
        at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:62)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:124)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

8月 16, 2024 9:55:40 上午 de.unijena.bioinf.ms.frontend.Run parseArgs
資訊: Running with following arguments: [summaries, --output=C:\0-SIRIUS_TEMP\20240816, --top-hit-summary, --top-k-summary=2]
8月 16, 2024 9:55:40 上午 de.unijena.bioinf.ms.backgroundruns.BackgroundRuns lambda$submitRunAndLockInstances$15
資訊: Locking Instances for Computation...
8月 16, 2024 9:55:40 上午 de.unijena.bioinf.ms.backgroundruns.BackgroundRuns lambda$submitRunAndLockInstances$15
資訊: ...All instances locked!
8月 16, 2024 9:55:42 上午 de.unijena.bioinf.jjobs.JJob lambda$logError$2
嚴重: <363>[NoSqlSummarySubToolJob-363] Failed!
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null
        at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlStructureSummaryWriter.writeStructureCandidate(NoSqlStructureSummaryWriter.java:110)
        at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:221)
        at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:62)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:124)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

8月 16, 2024 9:55:42 上午 de.unijena.bioinf.jjobs.JJob lambda$logError$2
嚴重: <364>[BackgroundRunJob-364] Failed!
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null
        at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlStructureSummaryWriter.writeStructureCandidate(NoSqlStructureSummaryWriter.java:110)
        at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:221)
        at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:62)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:124)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

8月 16, 2024 9:55:43 上午 de.unijena.bioinf.jjobs.JJob lambda$logWarn$5
警告: <422>[SpectrumAnnotationJJob-422] Cannot submit SubJob 'Job-427' , MasterJob 'SpectrumAnnotationJJob-422' already finished

**Comment by mfleisch** [comment]
Hey,
this issue  has been fixed on dev branch and will be fixed in v6.0.5 which is scheduled for release in the first september week. 

Ich case you want to check it aleady feel free to try the latest pre-release (https://github.com/sirius-ms/sirius/releases/tag/v6.0.5-SNAPSHOT).

I closed the issue as fixed. In case v6.0.5-SNAPSHOT does not fix it for you feel free to reopen it.
