### ISSUE TITLE
Issue with importing .mgf files to Sirius version 6.0.5

### ISSUE THREAD

**Issue by Heli-T** [sirius-ms/sirius#198]
Hi!

I am trying to import a .mgf file created with MZmine3 to Sirius 6.0.5. I have previously imported the same file to version 5.8.6 without any issues, but now if I try to import it to version 6.0.5, I get the following error: 

Error when importing data! Cause: java.lang.Exception: java.lang.IllegalArgumentException: URI has an authority component
java.lang.Exception: java.lang.IllegalArgumentException: URI has an authority component
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob.updateAndCheckIfDone(SseProgressJJob.java:128)
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:75)
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:64)
	at de.unijena.bioinf.sse.FluxToFlowBroadcast.lambda$onNext$7(FluxToFlowBroadcast.java:103)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at de.unijena.bioinf.sse.FluxToFlowBroadcast.onNext(FluxToFlowBroadcast.java:99)
	at de.unijena.bioinf.ms.nightsky.sdk.NightSkyClient.lambda$enableEventListening$3(NightSkyClient.java:198)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:446)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:533)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Best regards,
Heli Tirkkonen

**Comment by Heli-T** [comment]
Hi,

Sure! Here is a dropbox link to the non-working file, as github apparently doesn't allow .mgf files here:

https://www.dropbox.com/scl/fi/u5yrkix3bwlvuy53brqse/2024_05_31_S_lavendulae_Ymedia_SC_MeOH_CHCl3_detlim_2E4.mgf?rlkey=vmyh2lmcwutmg6pht26atj5rg&st=sc04i1b8&dl=0

**Comment by MartinHoffmannJena** [comment]
Thank you, the file imports for me without issues. Could you please share your operating system and the path of the sirius project (e.g. /home/martin/mySiriusProject.sirius)?

**Comment by Heli-T** [comment]
My operating system is Windows 10(64bit). Sirius is installed in the following directory: C:\Program Files\sirius. I have my data files on a network drive (\\utu.fi\verkkolevyt\).

Actually, now I tested moving one of my data files to the desktop and now it imports fine. It used to work from the network drive before in the previous version too.

**Comment by ValentinCledassou** [comment]
Same problem here, I try to import my mgf files into Sirius 6.0.5 (with Import command) but I have this :

Error when importing data! Cause: java.lang.Exception: java.lang.Exception: Cannot parse file 'Feces_DDA_NEG.mgf'
java.lang.Exception: java.lang.Exception: Cannot parse file 'Feces_DDA_NEG.mgf'
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob.updateAndCheckIfDone(SseProgressJJob.java:128)
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:75)
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:64)
	at de.unijena.bioinf.sse.FluxToFlowBroadcast.lambda$onNext$7(FluxToFlowBroadcast.java:103)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at de.unijena.bioinf.sse.FluxToFlowBroadcast.onNext(FluxToFlowBroadcast.java:99)
	at de.unijena.bioinf.ms.nightsky.sdk.NightSkyClient.lambda$enableEventListening$3(NightSkyClient.java:198)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:446)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:533)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

I had no problem in Sirius 5, my mgf file is on my desktop, not on a server

**Comment by khalednematallah** [comment]
Same problem here, my data file on desktop, not in network folder and I received this:

Error when importing data! Cause: java.lang.Exception: java.lang.Exception: Cannot parse file 'Spaindus 50.mgf'
java.lang.Exception: java.lang.Exception: Cannot parse file 'Spaindus 50.mgf'
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob.updateAndCheckIfDone(SseProgressJJob.java:128)
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:75)
	at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:64)
	at de.unijena.bioinf.sse.FluxToFlowBroadcast.lambda$onNext$7(FluxToFlowBroadcast.java:103)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at de.unijena.bioinf.sse.FluxToFlowBroadcast.onNext(FluxToFlowBroadcast.java:99)
	at de.unijena.bioinf.ms.nightsky.sdk.NightSkyClient.lambda$enableEventListening$3(NightSkyClient.java:198)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:446)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:533)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Sirius is installed in C:\Program Files\sirius

**Comment by MartinHoffmannJena** [comment]
Hi,

Could you please provide an mgf file that produces this error?

**Comment by khalednematallah** [comment]
https://livebueedu-my.sharepoint.com/:u:/g/personal/khaled_nematallah_bue_edu_eg/EVG7ZlCJdCdFtinMZ2QSv8IBTD7N2izgtYxu6t9zqDqz3g?e=VYEhLo

**Comment by mfleisch** [comment]
> same problem here
> 
> msp file exported from progenesis qi
> 
> Error when importing data! Cause: java.lang.Exception: java.lang.Exception: Cannot parse file 'testr.msp' java.lang.Exception: java.lang.Exception: Cannot parse file 'testr.msp' at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob.updateAndCheckIfDone(SseProgressJJob.java:128) at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:75) at de.unijena.bioinf.ms.nightsky.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:64) at de.unijena.bioinf.sse.FluxToFlowBroadcast.lambda$onNext$7(FluxToFlowBroadcast.java:103) at java.base/java.lang.Iterable.forEach(Unknown Source) at de.unijena.bioinf.sse.FluxToFlowBroadcast.onNext(FluxToFlowBroadcast.java:99) at de.unijena.bioinf.ms.nightsky.sdk.NightSkyClient.lambda$enableEventListening$3(NightSkyClient.java:198) at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:446) at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:533) at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
> 
>  testr.msp.mp4 
> please rename it from mp4 tp msp

Can you pls try zipping the msp file. I cannot download it with the mp4 workaround.

**Comment by mfleisch** [comment]
@ValentinCledassou @kailaw138 @Heli-T 
it is not unlikely that is is a path resolution issue. Could you maybe provide the path where the source file are located when import is failing as well as the operating system you are using. In case the path contains secret information please try to modify them bug try to keep information like special characters.

**Comment by khalednematallah** [comment]
I shared my file through a link, are you able to get it?
@mfleisch

**Comment by Heli-T** [comment]
> @ValentinCledassou @kailaw138 @Heli-T it is not unlikely that is is a path resolution issue. Could you maybe provide the path where the source file are located when import is failing as well as the operating system you are using. In case the path contains secret information please try to modify them bug try to keep information like special characters.

The path for my network drive, where it refuses to open the files is the following: \\utu.fi\verkkolevyt\Biokemian muokattu\NOVO interactions\Metabolomics\6600 data\2024_05_31\SIRIUS\S_lavendulae\S_lavendulae_Ymedia_SC_MeOH_CHCl3
My operating system is Windows(64bit).

**Comment by MartinHoffmannJena** [comment]
> I shared my file through a link, are you able to get it? @mfleisch

Hi, this mgf does not contain information about the charge, so SIRIUS does not know if this is positive or negative ion type. This information is critical and it is not possible to parse mgf files that don't contain information about the charge.

**Comment by MartinHoffmannJena** [comment]
@ValentinCledassou @kailaw138 

Please provide the files don't work for your and I will take a look at them as well

**Comment by ValentinCledassou** [comment]
Hi,

Thank you for your help, this is the link for my MGF files (work with the last version of Sirius 5 but not with Sirius 6, I have tried to move my files at different places on my computer, but that doesn't change)

https://www.swisstransfer.com/d/ea27d466-7272-4350-b152-1d2de0d1d216

**Comment by MartinHoffmannJena** [comment]
> Hi,
> 
> Thank you for your help @MartinHoffmannJena , this is the link for my MGF files (work with the last version of Sirius 5 but not with Sirius 6, I have tried to move my files at different places on my computer, but that doesn't change. I don't think that's a problem of files path)
> 
> https://www.swisstransfer.com/d/ea27d466-7272-4350-b152-1d2de0d1d216

Hi,

This mgf seems a bit weirdly formatted, which is the reason for the parsing error (multiple headers in a single line). Could you share what software/method exported this?

**Comment by ValentinCledassou** [comment]
Hello,

It's a python home-script which consisted to convert MSP files from workflow4metabolomics to MGF files for Sirius. I have not the python script, it belongs to a private service provider.

I hadn't problems of compatibility with the last version of Sirius 5.

**Comment by MartinHoffmannJena** [comment]
> Hello,
> 
> It's a python home-script which consisted to convert MSP files from workflow4metabolomics to MGF files for Sirius. I have not the python script, it belongs to a private service provider.
> 
> I hadn't problems of compatibility with the last version of Sirius 5.

Hi,

The mgf format specifies that multiple headers in one line are not allowed (https://www.matrixscience.com/help/data_file_help.html). SIRIUS 5 was sometimes able to parse these files by basically guessing some parameters (like charge) from the file name. This lead to partially faulty imports of those files which is why this functionality does not exist anymore.

Your service provider is currently producing invalid (per the convention) .mgf files, it would be best to ask them to fix that.
