### ISSUE TITLE
 The connection to the Sirius server cannot be established.

### ISSUE THREAD

**Issue by MounteZ22** [sirius-ms/sirius#205]
Hello, I’m sorry to bother you, but I couldn’t access the network service when trying to use Sirius today. I just started using Sirius, and the network connection was working fine after I installed it days ago. I’d like to know if this is an issue with my network settings or if it’s a problem with the server.
![D864F84E7BFA6E988368176A67E50392](https://github.com/user-attachments/assets/bf8f99ab-d5ff-458d-b789-e0cf7f5da1d0)

9月 27, 2024 5:20:21 下午 de.unijena.bioinf.rest.ProxyManager checkConnectionToUrl
警告: Connection error
java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at de.unijena.bioinf.rest.ProxyManager.checkConnectionToUrl(ProxyManager.java:299)
	at de.unijena.bioinf.rest.ProxyManager.checkExternal(ProxyManager.java:277)
	at de.unijena.bioinf.rest.ProxyManager.checkInternetConnection(ProxyManager.java:126)
	at de.unijena.bioinf.webapi.rest.RestAPI.lambda$checkConnection$9(RestAPI.java:203)
	at de.unijena.bioinf.rest.ProxyManager.consumeClient(ProxyManager.java:439)
	at de.unijena.bioinf.rest.ProxyManager.consumeClient(ProxyManager.java:432)
	at de.unijena.bioinf.webapi.rest.RestAPI.checkConnection(RestAPI.java:196)
	at de.unijena.bioinf.ms.gui.net.ConnectionMonitor$CheckJob.compute(ConnectionMonitor.java:182)
	at de.unijena.bioinf.ms.gui.net.ConnectionMonitor$CheckJob.compute(ConnectionMonitor.java:138)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:117)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.net.SocketTimeoutException: Connect timed out
		... 35 more

**Comment by mfleisch** [comment]
Which SIRIUS version are you using?

**Comment by MounteZ22** [comment]
> Which SIRIUS version and which operating system are you using?

Hello，I am using sirius 5.8.6 now . Actually, I initially downloaded version 6.0.4, but this version didn’t display the network service check window when I checked the connection. So, I downgraded back to Sirius 5.

**Comment by MounteZ22** [comment]
> Which SIRIUS version and which operating system are you using?
Sirius server is established now. Thank you for your concern.
