### ISSUE TITLE
Error when importing .mzml files

### ISSUE THREAD

**Issue by sra34** [sirius-ms/sirius#209]
**Bug description**
I get the following error message every time when trying to upload .mzml files into SIRIUS (v. 6.0.6):

Error when importing data! Cause: java.lang.Exception: com.fasterxml.jackson.databind.JsonMappingException: Index 0 out of bounds for length 0 (through reference chain: de.unijena.bioinf.ms.persistence.model.core.feature.AlignedFeatures["detectedAdducts"]->de.unijena.bioinf.ms.persistence.model.core.feature.DetectedAdducts["detectedAdductsList"]->java.util.ArrayList[0]->de.unijena.bioinf.ms.persistence.model.core.feature.DetectedAdduct$DetectedAdductBuilder["adduct"])
java.lang.Exception: com.fasterxml.jackson.databind.JsonMappingException: Index 0 out of bounds for length 0 (through reference chain: de.unijena.bioinf.ms.persistence.model.core.feature.AlignedFeatures["detectedAdducts"]->de.unijena.bioinf.ms.persistence.model.core.feature.DetectedAdducts["detectedAdductsList"]->java.util.ArrayList[0]->de.unijena.bioinf.ms.persistence.model.core.feature.DetectedAdduct$DetectedAdductBuilder["adduct"])
	at io.sirius.ms.sdk.jjobs.SseProgressJJob.updateAndCheckIfDone(SseProgressJJob.java:128)
	at io.sirius.ms.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:75)
	at io.sirius.ms.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:64)
	at io.sirius.ms.sse.FluxToFlowBroadcast.lambda$onNext$7(FluxToFlowBroadcast.java:103)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at io.sirius.ms.sse.FluxToFlowBroadcast.onNext(FluxToFlowBroadcast.java:99)
	at io.sirius.ms.sdk.SiriusClient.lambda$enableEventListening$3(SiriusClient.java:203)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:446)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:533)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

The .mzml files have been centroided in msconvert, with msLevel = 1 and 2 data. These same files were successfully imported in SIRIUS version 5, so I am not sure if there is an issue with my files in the newer version. 

Here are some example .mzml files that I have tried to import and which have successfully been imported in version 5:

https://drive.google.com/file/d/1-7CneFejGiep-UMK1zpOntd5H9XERTzr/view?usp=sharing, https://drive.google.com/file/d/1wYCKx-zjwa_Zhd7Dusp_OgeP3CRFnr-2/view?usp=sharing, https://drive.google.com/file/d/1yKJskFTueWF6dihputcRl8STJZdrlreL/view?usp=sharing

I am on macOS (Sequoia; 15.0.1), Intel i7, 16 GB. 

Thank you for your help!

**Comment by MartinHoffmannJena** [comment]
Thank you for the detailed report, we are looking at this

**Comment by sra34** [comment]
Hi there -- I downloaded the latest release (v 6.0.7) and imported the files again. I got the same error message but it seemed to work and progress to the next step. I am not sure if I trust it though. Any thoughts? Would you be able to test the files included in the above comment with the newest version release and see how it looks? 

Thank you for your continued support.

**Comment by MMetz9** [comment]
Hi are there any updates available about fixing this issue? I'm using the latest release and getting the same error but mine does not progress to the next step. I've tried running SIRIUS GUI on both a PC and Mac to import the data but same error pops up.
