### ISSUE TITLE
Error while importing single compounds ms and ms/ms .txt files to Sirius 6.0.6

### ISSUE THREAD

**Issue by DMutithu** [sirius-ms/sirius#211]
I have Sirius 6.0.6
When importing .txt files with the ms and ms/ms information I got the following error.
"java.lang.Exception: java.lang.Exception: Cannot parse file 'AlignID450_ms.txt'
	at io.sirius.ms.sdk.jjobs.SseProgressJJob.updateAndCheckIfDone(SseProgressJJob.java:128)
	at io.sirius.ms.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:75)
	at io.sirius.ms.sdk.jjobs.SseProgressJJob$1.onNext(SseProgressJJob.java:64)
	at io.sirius.ms.sse.FluxToFlowBroadcast.lambda$onNext$7(FluxToFlowBroadcast.java:103)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at io.sirius.ms.sse.FluxToFlowBroadcast.onNext(FluxToFlowBroadcast.java:99)
	at io.sirius.ms.sdk.SiriusClient.lambda$enableEventListening$3(SiriusClient.java:203)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:446)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:533)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)"

Does anyone know how to go around this error?

**Comment by MartinHoffmannJena** [comment]
Can you please share this file?

**Comment by DMutithu** [comment]
Please find attached.

[AlignID450_ms.txt](https://github.com/user-attachments/files/17523686/AlignID450_ms.txt)
[AlignID450_msms1.txt](https://github.com/user-attachments/files/17523687/AlignID450_msms1.txt)

**Comment by MartinHoffmannJena** [comment]
Your files not contain enough information, such as the ion mode, mass etc. 

Please check this entry for how input to SIRIUS should look like:

https://v6.docs.sirius-ms.io/io/#input
