### ISSUE TITLE
[BUG] -command login error

### ISSUE THREAD

**Issue by nibingwei123** [sirius-ms/sirius#212]
I run ：sirius login -u xxx -p 
error:
PM de.unijena.bioinf.ms.frontend.SiriusCLIApplication run
SEVERE: Unexpected Error!
picocli.CommandLine$UnmatchedArgumentException: Unmatched argument at index 4:

**Comment by MartinHoffmannJena** [comment]
Hi, which SIRIUS version are you using?

**Comment by ts-dangelo** [comment]
@MartinHoffmannJena  

Hi I am having the same issue, but it is a part of a bigger goal.

[tdangelo@cfe2 singularity_tests]$ sirius login -u tdangelo -p XXXXXXX
SIRIUS is running in headless mode. GUI feature are not available!
Apr 03, 2025 1:32:54 PM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
Apr 03, 2025 1:32:54 PM de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>
INFO: Sirius Workspace Successfull initialized at: /home/tdangelo/.sirius-6.1
Apr 03, 2025 1:32:54 PM de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>
INFO: You run SIRIUS 6.1.1 on linux_amd64
Apr 03, 2025 1:32:54 PM de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>
INFO: You run SIRIUS in 'CLI' mode.
Apr 03, 2025 1:32:54 PM de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>
INFO: Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v2.10.8.29
Apr 03, 2025 1:32:54 PM de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>
INFO: Treebuilder priorities loaded from 'sirius.properties' are: [CLP, GUROBI, CPLEX]
Apr 03, 2025 1:32:54 PM de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>
INFO: CPU check done. 2 cores that handle 4 threads were found.
Apr 03, 2025 1:32:54 PM de.unijena.bioinf.ChemistryBase.jobs.SiriusJobs getGlobalJobManager
INFO: Job manager successful initialized with 3 CPU thread(s) and 3 IO thread(s).
Apr 03, 2025 1:32:54 PM de.unijena.bioinf.rest.ProxyManager decorateWithPoolSettings
INFO: Starting http Client with MaxPerRoute=3 / maxTotal=5 (CPU-Threads=3).
Apr 03, 2025 1:32:55 PM de.unijena.bioinf.auth.AuthService getToken
WARNING: No login Found: Not Logged in, No valid refresh token Available
Apr 03, 2025 1:32:55 PM de.unijena.bioinf.ms.frontend.core.ApplicationCore <clinit>
INFO: Web API initialized.
Enter value for --password (Console password input.): 
Apr 03, 2025 1:33:05 PM de.unijena.bioinf.ms.frontend.SiriusCLIApplication run
SEVERE: Unexpected Error!
picocli.CommandLine$UnmatchedArgumentException: Unmatched argument at index 4: 'XXXXXXX'
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13662)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13614)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13904)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13800)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13591)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13559)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13454)
	at picocli.CommandLine.parseArgs(CommandLine.java:1552)
	at de.unijena.bioinf.ms.frontend.Run.parseArgs(Run.java:82)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:143)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.runMain(SiriusCLIApplication.java:77)
	at de.unijena.bioinf.ms.middleware.SiriusMiddlewareApplication.main(SiriusMiddlewareApplication.java:222)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:102)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)

Apr 03, 2025 1:33:05 PM de.unijena.bioinf.ms.frontend.SiriusCLIApplication lambda$configureShutDownHook$1
INFO: CLI shut down hook: SIRIUS is cleaning up threads and shuts down...


 **Unmatched argument at index 4: 'XXXXXXX' - the XXXXXX is my password. So it is not recognizing the CLI input
 after -p as an input, not the case for -u**
 
 I am using Sirius 6.1.1

 which sirius /mnt/modules/bin/sirius/6.1.1/bin/sirius
 
 
 
**I am trying to login via CLI so that I can get a token for running sirius inside apptainer. The
server I am using does not have all of the libraries I need for sirius, so I am trying the container route.**


I use this definition to build a SIF file and run the demo-data provided for sirius

Bootstrap: docker
From: public.ecr.aws/u7h0g2s9/continuumio/miniconda3:23.5.2-0

%post
    # Update conda and install dependencies
    conda update conda -y
    conda init bash
    conda create -n sirius-env python=3.8 -y

    # Install SIRIUS and OpenJDK using conda run (ensures correct activation)
    conda run -n sirius-env conda install -c conda-forge sirius-ms -y
    conda run -n sirius-env conda install -c conda-forge openjdk -y

    # Create necessary directories
    mkdir -p /data/results

%files
    /demo-data/mgf/laudanosine.mgf /data/

%environment
    export PATH="/opt/conda/bin:$PATH"
    export CONDA_DEFAULT_ENV=sirius-env
    export DATA_DIR="/data"

%runscript
    conda run -n sirius-env sirius --input ${DATA_DIR}/*.mgf --output ${DATA_DIR}/results/demo.sirius formula -p orbitrap fingerprint compound-classes write-summaries --output demo


apptainer build sirius.sif sirius.def


When I run it, it becomes apparent I need to login. My goal is to use singularity and a scheduler
to run many samples in parrallel on a server, so I need to get a token, or some way to make the 
login requirements high-throughput:

apptainer run --bind /demo-data:/data:rw sirius.sif

   
 Apr 03, 2025 5:29:30 PM de.unijena.bioinf.ms.frontend.Run parseArgs
INFO: Running with following arguments: [--input, /data/laudanosine.mgf, --output, /data/results/demo.sirius, formula, -p, orbitrap, fingerprint, compound-classes, write-summaries, --output, demo]
Apr 03, 2025 5:29:30 PM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <0>[InputExpanderJJob-0] Running post processing
Apr 03, 2025 5:29:30 PM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <0>[InputExpanderJJob-0] Running cleanup
Apr 03, 2025 5:29:30 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <1>[InputExpanderJJob-1] Expanding Input Files: '/data/laudanosine.mgf'...
Apr 03, 2025 5:29:30 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <1>[InputExpanderJJob-1] ...Input Files successfully expanded!
Apr 03, 2025 5:29:30 PM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <1>[InputExpanderJJob-1] Running post processing
Apr 03, 2025 5:29:30 PM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <1>[InputExpanderJJob-1] Running cleanup
Apr 03, 2025 5:29:32 PM de.unijena.bioinf.ms.frontend.workflow.ToolChainWorkflow run
INFO: Creating Toolchain InstanceBuffer of size 15
Apr 03, 2025 5:29:32 PM de.unijena.bioinf.chemdb.custom.CustomDatabases load
INFO: Loaded custom databases: 
Apr 03, 2025 5:29:33 PM de.unijena.bioinf.jjobs.JJob lambda$logWarn$7
WARNING: <14>[CanopusSubToolJob-14 | <Awaiting Instance>] Required Job 'FingerprintSubToolJob-13 | FEATURE_1 (695683386943255813)' finished with unexpected state 'FAILED'.
Apr 03, 2025 5:29:33 PM de.unijena.bioinf.jjobs.JJob lambda$logError$2
SEVERE: <13>[FingerprintSubToolJob-13 | FEATURE_1 (695683386943255813)] Failed!
java.lang.NullPointerException: Service URL is null. This might be caused by a missing login.
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.getBaseURI(AbstractCsiClient.java:82)
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.buildWebapiURI(AbstractCsiClient.java:72)
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.buildVersionSpecificWebapiURI(AbstractCsiClient.java:76)
	at de.unijena.bioinf.ms.rest.client.fingerid.FingerIdClient.lambda$getFingerIdData$0(FingerIdClient.java:67)
	at de.unijena.bioinf.ms.rest.client.AbstractClient.execute(AbstractClient.java:156)
	at de.unijena.bioinf.ms.rest.client.fingerid.FingerIdClient.getFingerIdData(FingerIdClient.java:66)
	at de.unijena.bioinf.webapi.rest.RestAPI.lambda$getFingerIdDataUncached$29(RestAPI.java:432)
	at de.unijena.bioinf.rest.ProxyManager.applyClient(ProxyManager.java:468)
	at de.unijena.bioinf.rest.ProxyManager.applyClient(ProxyManager.java:461)
	at de.unijena.bioinf.webapi.rest.RestAPI.getFingerIdDataUncached(RestAPI.java:432)
	at de.unijena.bioinf.webapi.AbstractWebAPI.lambda$getFingerIdData$1(AbstractWebAPI.java:81)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at de.unijena.bioinf.webapi.AbstractWebAPI.getFingerIdData(AbstractWebAPI.java:79)
	at de.unijena.bioinf.projectspace.AbstractProjectSpaceManager.writeFingerIdDataIfMissing(AbstractProjectSpaceManager.java:43)
	at de.unijena.bioinf.ms.frontend.subtools.fingerprint.FingerprintSubToolJob.lambda$computeAndAnnotateResult$5(FingerprintSubToolJob.java:87)
	at de.unijena.bioinf.rest.NetUtils.lambda$tryAndWait$2(NetUtils.java:79)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:93)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:78)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:74)
	at de.unijena.bioinf.ms.frontend.subtools.fingerprint.FingerprintSubToolJob.computeAndAnnotateResult(FingerprintSubToolJob.java:87)
	at de.unijena.bioinf.ms.frontend.subtools.InstanceJob.compute(InstanceJob.java:79)
	at de.unijena.bioinf.ms.frontend.subtools.InstanceJob.compute(InstanceJob.java:43)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:124)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Apr 03, 2025 5:29:33 PM de.unijena.bioinf.jjobs.JJob lambda$logError$1
SEVERE: <13>[FingerprintSubToolJob-13 | FEATURE_1 (695683386943255813)] ToolChain Job failed due to: java.lang.NullPointerException: Service URL is null. This might be caused by a missing login.
Apr 03, 2025 5:29:33 PM de.unijena.bioinf.jjobs.JJob lambda$logWarn$5
WARNING: <14>[CanopusSubToolJob-14 | <Awaiting Instance>] ToolChain Job canceled due to: java.util.concurrent.CancellationException: Job 'CanopusSubToolJob-14 | <Awaiting Instance>' canceled before submission to executor, Most likely because of a failing required Job.
Apr 03, 2025 5:29:33 PM de.unijena.bioinf.FragmentationTreeConstruction.computation.tree.ilp.CLPModel_JNI <clinit>
INFO: Loading CBC libs for detected architecture `linux-amd64` from prefix '/linux-x86-64/' with '10' jar and '10' path dependencies.
Apr 03, 2025 5:29:34 PM de.unijena.bioinf.jjobs.JJob lambda$logWarn$7
WARNING: <9>[CanopusSubToolJob-9 | <Awaiting Instance>] Required Job 'FingerprintSubToolJob-8 | FEATURE_1 (695686439975729763)' finished with unexpected state 'FAILED'.
Apr 03, 2025 5:29:34 PM de.unijena.bioinf.jjobs.JJob lambda$logError$2
SEVERE: <8>[FingerprintSubToolJob-8 | FEATURE_1 (695686439975729763)] Failed!
java.lang.NullPointerException: Service URL is null. This might be caused by a missing login.
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.getBaseURI(AbstractCsiClient.java:82)
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.buildWebapiURI(AbstractCsiClient.java:72)
	at de.unijena.bioinf.ms.rest.client.AbstractCsiClient.buildVersionSpecificWebapiURI(AbstractCsiClient.java:76)
	at de.unijena.bioinf.ms.rest.client.fingerid.FingerIdClient.lambda$getFingerIdData$0(FingerIdClient.java:67)
	at de.unijena.bioinf.ms.rest.client.AbstractClient.execute(AbstractClient.java:156)
	at de.unijena.bioinf.ms.rest.client.fingerid.FingerIdClient.getFingerIdData(FingerIdClient.java:66)
	at de.unijena.bioinf.webapi.rest.RestAPI.lambda$getFingerIdDataUncached$29(RestAPI.java:432)
	at de.unijena.bioinf.rest.ProxyManager.applyClient(ProxyManager.java:468)
	at de.unijena.bioinf.rest.ProxyManager.applyClient(ProxyManager.java:461)
	at de.unijena.bioinf.webapi.rest.RestAPI.getFingerIdDataUncached(RestAPI.java:432)
	at de.unijena.bioinf.webapi.AbstractWebAPI.lambda$getFingerIdData$1(AbstractWebAPI.java:81)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at de.unijena.bioinf.webapi.AbstractWebAPI.getFingerIdData(AbstractWebAPI.java:79)
	at de.unijena.bioinf.projectspace.AbstractProjectSpaceManager.writeFingerIdDataIfMissing(AbstractProjectSpaceManager.java:43)
	at de.unijena.bioinf.ms.frontend.subtools.fingerprint.FingerprintSubToolJob.lambda$computeAndAnnotateResult$5(FingerprintSubToolJob.java:87)
	at de.unijena.bioinf.rest.NetUtils.lambda$tryAndWait$2(NetUtils.java:79)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:93)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:78)
	at de.unijena.bioinf.rest.NetUtils.tryAndWait(NetUtils.java:74)
	at de.unijena.bioinf.ms.frontend.subtools.fingerprint.FingerprintSubToolJob.computeAndAnnotateResult(FingerprintSubToolJob.java:87)
	at de.unijena.bioinf.ms.frontend.subtools.InstanceJob.compute(InstanceJob.java:79)
	at de.unijena.bioinf.ms.frontend.subtools.InstanceJob.compute(InstanceJob.java:43)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:124)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Apr 03, 2025 5:29:34 PM de.unijena.bioinf.jjobs.JJob lambda$logError$1
SEVERE: <8>[FingerprintSubToolJob-8 | FEATURE_1 (695686439975729763)] ToolChain Job failed due to: java.lang.NullPointerException: Service URL is null. This might be caused by a missing login.



**So i think I need to login and make a login token I can use as input in the singularity definition?**

Thanks,
Tim D'Angelo

**Comment by MartinHoffmannJena** [comment]
Hi,

This basically can not happen, or at least I don't know of any way it could. 

Would your be able to share the two .Sirius projects with me? I might be able to understand what happened

**Comment by MartinHoffmannJena** [comment]
Hi,

if using the -p option you are not mean to write your password after it, which is what that errors says. If you submit sirius login -u <user> -p, you are then prompted to type your password into the console.

For your case, you can use sirius login -u <user> ---password-env=env to supply the password via an environment variable. See sirius login --help

**Comment by nibingwei123** [comment]
Thank you for your guidance. I solved it.



At 2025-04-04 02:22:08, "Martin Hoffmann" ***@***.***> wrote:

Hi,

if using the -p option you are not mean to write your password after it, which is what that errors says. If you submit sirius login -u -p, you are then prompted to type your password into the console.

For your case, you can use sirius login -u ---password-env=env to supply the password via an environment variable. See sirius login --help

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

MartinHoffmannJena left a comment (sirius-ms/sirius#212)

Hi,

if using the -p option you are not mean to write your password after it, which is what that errors says. If you submit sirius login -u -p, you are then prompted to type your password into the console.

For your case, you can use sirius login -u ---password-env=env to supply the password via an environment variable. See sirius login --help
